AWSTemplateFormatVersion: '2010-09-09'
Description: 'Public + Private Subnets'

Parameters:
  NamePrefix:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PublicSubnetCidr:
    Type: String
  PrivateSubnetCidr:
    Type: String
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name

Resources:
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref PublicSubnetCidr
      AvailabilityZone: !Ref AvailabilityZone
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${NamePrefix}-public-subnet'
        - Key: Tier
          Value: public

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref PrivateSubnetCidr
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: Name
          Value: !Sub '${NamePrefix}-private-subnet'
        - Key: Tier
          Value: private

Outputs:
  PublicSubnetId:
    Value: !Ref PublicSubnet
  PrivateSubnetId:
    Value: !Ref PrivateSubnet
