AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC + Internet Gateway'

Parameters:
  NamePrefix:
    Type: String
  VpcCidr:
    Type: String

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${NamePrefix}-vpc'

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${NamePrefix}-igw'

  IgwAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

Outputs:
  VpcId:
    Value: !Ref Vpc
  InternetGatewayId:
    Value: !Ref InternetGateway
