AWSTemplateFormatVersion: '2010-09-09'
Description: 'Public + Private Security Groups'

Parameters:
  NamePrefix:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  MyIp:
    Type: String
    AllowedPattern: '^(\d{1,3}\.){3}\d{1,3}/\d{1,2}$'

Resources:
  PublicSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from specific IP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIp
          Description: SSH from my IP
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound
      Tags:
        - Key: Name
          Value: !Sub '${NamePrefix}-public-sg'

  PrivateSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH only from Public SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicSg
          Description: SSH from Public EC2
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound
      Tags:
        - Key: Name
          Value: !Sub '${NamePrefix}-private-sg'

Outputs:
  PublicSgId:
    Value: !Ref PublicSg
  PrivateSgId:
    Value: !Ref PrivateSg
